// app/utils/taxonomy.ts
// İhaleciBurada B2B E-İhale ve Tedarik Pazaryeri Standart Taksonomisi

export const ALL_81_CITIES = [
  'Adana', 'Adıyaman', 'Afyonkarahisar', 'Ağrı', 'Aksaray', 'Amasya', 'Ankara', 'Antalya',
  'Ardahan', 'Artvin', 'Aydın', 'Balıkesir', 'Bartın', 'Batman', 'Bayburt', 'Bilecik',
  'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Çanakkale', 'Çankırı', 'Çorum',
  'Denizli', 'Diyarbakır', 'Düzce', 'Edirne', 'Elazığ', 'Erzincan', 'Erzurum', 'Eskişehir',
  'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkari', 'Hatay', 'Iğdır', 'Isparta', 'İstanbul',
  'İzmir', 'Kahramanmaraş', 'Karabük', 'Karaman', 'Kars', 'Kastamonu', 'Kayseri', 'Kırıkkale',
  'Kırklareli', 'Kırşehir', 'Kilis', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya', 'Manisa',
  'Mardin', 'Mersin', 'Muğla', 'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Osmaniye', 'Rize',
  'Sakarya', 'Samsun', 'Siirt', 'Sinop', 'Sivas', 'Şanlıurfa', 'Şırnak', 'Tekirdağ',
  'Tokat', 'Trabzon', 'Tunceli', 'Uşak', 'Van', 'Yalova', 'Yozgat', 'Zonguldak'
];

export const ALL_40_CATEGORIES = [
  { id: 1, name: 'İnşaat - Altyapı - Üstyapı - Yapım İşi ve Yıkım İhaleleri', short: 'İnşaat & Altyapı', icon: '🏗️' },
  { id: 2, name: 'Sağlık - İlaç - Kozmetik - Medikal İhaleleri', short: 'Sağlık & Medikal', icon: '💊' },
  { id: 3, name: 'Gıda - Tarım Ürünleri - Yiyecek - İçecek İhaleleri', short: 'Gıda & Tarım', icon: '🌾' },
  { id: 4, name: 'Tıbbi Cihaz - Laboratuvar - Hastane Ekipmanları İhaleleri', short: 'Tıbbi Cihaz & Hastane', icon: '🩺' },
  { id: 5, name: 'Kanalizasyon - Boru - Su - Doğalgaz - Sıhhi Tesisat İhaleleri', short: 'Kanalizasyon & Su', icon: '🚰' },
  { id: 6, name: 'Enerji - Aydınlatma - Sinyalizasyon - Elektrik Tesisatı İhaleleri', short: 'Enerji & Elektrik', icon: '⚡' },
  { id: 7, name: 'Akaryakıt - Gazyağı - Madeni Yağ İhaleleri', short: 'Akaryakıt & Madeni Yağ', icon: '⛽' },
  { id: 8, name: 'Endüstriyel Makine - Motor - Konveyör İhaleleri', short: 'Endüstriyel Makine', icon: '⚙️' },
  { id: 9, name: 'Yazılım - Bilgi Yönetim Hizmetleri - Bilişim İhaleleri', short: 'Yazılım & Bilişim', icon: '💻' },
  { id: 10, name: 'Nakliye - Taşımacılık Hizmetleri - Servis İhaleleri', short: 'Nakliye & Lojistik', icon: '🚚' },
  { id: 11, name: 'Mobilya - Beyaz Eşya - Mutfak - Züccaciye İhaleleri', short: 'Mobilya & Ofis', icon: '🪑' },
  { id: 12, name: 'Hırdavat - Nalburiye - Metal ve Plastik Ürünler İhaleleri', short: 'Hırdavat & Metal', icon: '🔩' },
  { id: 13, name: 'Yangın Algılama - Söndürme - İhbar Sistemleri İhaleleri', short: 'Yangın & Güvenlik', icon: '🧯' },
  { id: 14, name: 'Kimyasal Maddeler - Dezenfektan - Gübre İhaleleri', short: 'Kimyasal & Gübre', icon: '🧪' },
  { id: 15, name: 'Matbaa - Toner - Kartuş - Ambalaj - Kırtasiye İhaleleri', short: 'Matbaa & Kırtasiye', icon: '📦' },
  { id: 16, name: 'Kent Mobilyaları - Prefabrik Yapılar - Doğrama İhaleleri', short: 'Kent Mobilyaları', icon: '🏙️' },
  { id: 17, name: 'Mühendislik - Mimarlık - Danışmanlık İhaleleri', short: 'Mühendislik & Mimarlık', icon: '📐' },
  { id: 18, name: 'Madencilik - Doğal Kaynaklar - Sondaj İhaleleri', short: 'Madencilik & Sondaj', icon: '⛏️' },
  { id: 19, name: 'Asansör - Yapı Otomasyon - Mekanik Güvenlik İhaleleri', short: 'Asansör & Otomasyon', icon: '🛗' },
  { id: 20, name: 'Klima - Soğutma - Isıtma - Havalandırma Tesisatı İhaleleri', short: 'Klima & Havalandırma', icon: '❄️' },
  { id: 21, name: 'Savunma Sanayi, Silah - Denizcilik - Havacılık İhaleleri', short: 'Savunma & Havacılık', icon: '🛡️' },
  { id: 22, name: 'Taşıt - İş Makinesi - Yedek Parça İhaleleri', short: 'Taşıt & İş Makinesi', icon: '🚜' },
  { id: 23, name: 'Turizm - Ödüllendirme Hizmetleri - Organizasyon İhaleleri', short: 'Turizm & Organizasyon', icon: '🎪' },
  { id: 24, name: 'Reklam - Tabela - Billboard - Tanıtım Materyalleri İhaleleri', short: 'Reklam & Tanıtım', icon: '📢' },
  { id: 25, name: 'Ormancılık, Bahçıvanlık, Bitki, Kozalak - Peyzaj İhaleleri', short: 'Ormancılık & Peyzaj', icon: '🌲' },
  { id: 26, name: 'Hayvancılık - Veterinerlik - Hayvan Yemi İhaleleri', short: 'Hayvancılık & Yem', icon: '🐄' },
  { id: 27, name: 'Sanat Eserleri - Müzik Aletleri - Heykel - Maket İhaleleri', short: 'Sanat & Heykel', icon: '🎨' },
  { id: 28, name: 'Odun - Kömür - Katıyakıt İhaleleri', short: 'Odun & Kömür', icon: '🪵' },
  { id: 29, name: 'Hazır Yemek - Lokantacılık İhaleleri', short: 'Hazır Yemek & İkram', icon: '🍽️' },
  { id: 30, name: 'Elektronik - Ölçü Aletleri - İletişim - Bilgisayar İhaleleri', short: 'Elektronik & Bilgisayar', icon: '🖥️' },
  { id: 31, name: 'Uydu Takip - Kamera - Scada - Haberleşme Sistemleri İhaleleri', short: 'Kamera & Güvenlik', icon: '📹' },
  { id: 32, name: 'Temizlik - İlaçlama - Geri Dönüşüm İhaleleri', short: 'Temizlik & Geri Dönüşüm', icon: '🧹' },
  { id: 33, name: 'Tekstil - Giyim - Spor Ekipmanları İhaleleri', short: 'Tekstil & Giyim', icon: '👕' },
  { id: 34, name: 'İş Sağlığı - İş Güvenliği ve Ekipmanları İhaleleri', short: 'İş Sağlığı & Güvenliği', icon: '⛑️' },
  { id: 35, name: 'Özel Güvenlik - Koruma - Bekçilik İhaleleri', short: 'Özel Güvenlik', icon: '👮' },
  { id: 36, name: 'Eğitim - Araştırma - Anket - Tercümanlık İhaleleri', short: 'Eğitim & Tercümanlık', icon: '📚' },
  { id: 37, name: 'İşletmecilik - İşçilik - Sosyal Hizmetler İhaleleri', short: 'İşletmecilik & Hizmet', icon: '🤝' },
  { id: 38, name: 'Sigortacılık - Mali ve Hukuki Hizmetler İhaleleri', short: 'Sigorta & Finans', icon: '⚖️' },
  { id: 39, name: 'Menkul Mallar - Araç Satışı ve Hurda İhaleleri', short: 'Araç & Hurda Satışı', icon: '🚗' },
  { id: 40, name: 'Gayrimenkul, Arsa Satışı, İşyeri ve Kantin İhaleleri', short: 'Gayrimenkul & Arsa', icon: '🏢' }
];

export const CATEGORY_SUBCATEGORIES_MAP: Record<number, string[]> = {
  1: ['Bina Yapımı & Taahhüt', 'Yol, Köprü & Viyadük', 'Hafriyat, Kazı & Dolgu', 'Çelik Konstrüksiyon', 'Prefabrik Yapılar', 'İzolasyon & Su Yalıtımı', 'Boya, Sıva & Alçıpan', 'Tadilat & Restorasyon'],
  2: ['Tıbbi Cihaz & Sarf Malzemeleri', 'İlaç & Serum Tedariği', 'Laboratuvar Kitleri & Reaktifler', 'Ortopedi & Protez Ürünleri', 'Kişisel Koruyucu Hijyen', 'Dental & Diş Sağlığı'],
  3: ['Kuru Gıda, Bakliyat & Hububat', 'Et, Tavuk & Şarküteri', 'Süt & Süt Ürünleri', 'Sebze & Meyve Toptan', 'Un, Şeker & Yağ', 'Konserve, Salça & Sos', 'Dondurulmuş Gıda'],
  4: ['Görüntüleme & Radyoloji (MR, CT)', 'Hasta Başı Monitörleri', 'Cerrahi El Aletleri', 'Sterilizatör & Otoklav', 'Hastane Yatağı & Mobilyası', 'Laboratuvar Analiz Cihazları'],
  5: ['Kanalizasyon & Altyapı Boruları', 'İçme Suyu Şebekesi', 'Doğalgaz Boru & Tesisatı', 'Sıhhi Tesisat & Armatürler', 'Pompalar & Hidroforlar', 'Vana, Sayaç & Ek Parçalar'],
  6: ['Güneş Enerjisi (GES) Sistemleri', 'Trafo, Pano & Kablolar', 'Sokak & Çevre Aydınlatma', 'İç Mekan LED Aydınlatma', 'Jeneratör & Kesintisiz Güç Kaynağı', 'Elektrik Tesisat Malzemeleri'],
  7: ['Motorin & Mazot Alımı', 'Kurşunsuz Benzin', 'Madeni Yağ & Gres', 'LPG & Otogaz', 'Gazyağı & Özel Yakıtlar'],
  8: ['CNC & Takım Tezgahları', 'Kompresör & Basınçlı Hava', 'Konveyör & Bant Sistemleri', 'Endüstriyel Motor & Redüktör', 'Paketleme & Dolum Makineleri', 'Hidrolik & Pnömatik Aksam'],
  9: ['Özel Yazılım Geliştirme', 'ERP & Kurumsal Yazılımlar', 'Bulut Sunucu & Hosting', 'Siber Güvenlik & Firewall', 'Veri Tabanı & Yedekleme', 'Mobil Uygulama Geliştirme'],
  10: ['Şehirlerarası Karayolu Nakliye', 'Personel & Öğrenci Servis Taşımacılığı', 'Denizyolu & Konteyner', 'Havayolu Kargo', 'Depolama & Lojistik Dağıtım', 'Soğuk Hava Zinciri Taşımacılığı'],
  11: ['Ofis & Büro Mobilyaları', 'Mutfak Ekipmanları & Endüstriyel Mutfak', 'Beyaz Eşya & Ankastre', 'Otel & Yurt Mobilyaları', 'Depo & Arşiv Raf Sistemleri', 'Züccaciye & Porselen'],
  12: ['Civata, Somun & Bağlantı Elemanları', 'El Aletleri & Güç Aletleri', 'Sac, Profil & Demir Ürünleri', 'Plastik Hammadde & Boru', 'Kilit, Menteşe & Nalburiye', 'Boya Tabancası & Aşındırıcılar'],
  13: ['Yangın Algılama & İhbar Panelleri', 'Otomatik Sprinkler Söndürme', 'Yangın Tüpleri & Dolapları', 'Davlumbaz Söndürme Sistemleri', 'Gazlı Söndürme (FM200)', 'Yangın Kapıları & Kaçış Donanımları'],
  14: ['Endüstriyel Kimyasallar', 'Tarımsal Gübreler & Zirai İlaç', 'Su Şartlandırma Kimyasalları', 'Yüzey Temizleme Kimyasalları', 'Havuz Kimyasalları', 'Laboratuvar Saf Kimyasalları'],
  15: ['Ofset & Dijital Matbaa Baskısı', 'Orijinal & Muadil Toner/Kartuş', 'Koli, Karton Kutu & Ambalaj', 'Kağıt, Fotokopi & Kırtasiye', 'Etiket, Barkod & Ribon', 'Promosyon Ürünleri & Baskı'],
  16: ['Park & Bahçe Kent Mobilyaları', 'Prefabrik Şantiye & Ofis Yapıları', 'Alüminyum & PVC Doğrama', 'Otobüs Durağı & Kamelya', 'Çocuk Oyun Parkı Ekipmanları', 'Güvenlik Kulübeleri'],
  17: ['Statik & Betonarme Projelendirme', 'Mimari Tasarım & 3D Modelleme', 'Zemin Etüdü & Geoteknik', 'Mekanik & Elektrik Proje Çizimi', 'Harita & İmar Danışmanlığı', 'Teknik Müşavirlik & Kontrollük'],
  18: ['Sondaj & Kuyu Açma Hizmetleri', 'Mermer, Granit & Taş Ocakları', 'Maden Çıkarma & Kırma-Eleme', 'Kömür & Linyit Ocak İşletmeciliği', 'Jeolojik Etüt & Rezerv Tespiti'],
  19: ['Yolcu & Yük Asansörleri', 'Yürüyen Merdiven & Bantlar', 'Bina Otomasyon Sistemleri (BMS)', 'Otomatik Kapı & Bariyer Sistemleri', 'Asansör Periyodik Bakım & Revizyon'],
  20: ['Merkezi VRF/VRV Klima Sistemleri', 'Chiller Soğutma Grupları', 'Havalandırma Kanalları & Menfezler', 'Kazan Dairesi & Isıtma Tesisatı', 'Hassas Kontrollü Sistem Klimaları', 'Rooftop Paket Klimalar'],
  21: ['Savunma Elektroniği & İletişim', 'Deniz Araçları & Bot Bakım-Onarım', 'Havacılık Yedek Parça & Sarf', 'Askeri Üniforma & Taktik Donanım', 'Balistik Koruyucu Yelek & Kask'],
  22: ['Binek & Ticari Araç Alımı', 'İş Makinesi Alım & Kiralama', 'Otomotiv Orijinal Yedek Parça', 'Kamyon, Çekici & Dorse', 'Lastik, Akü & Filtre Setleri', 'Araç Periyodik Bakım & Onarım'],
  23: [
    'Düğün, Nişan, Kına & Nikah Organizasyonu',
    'Evlilik Teklifi & Doğum Günü Organizasyonları',
    'Toplu Yeme-İçme & İftar Organizasyonları',
    'Konser, Festival, Sahne & Müzik Organizasyonları',
    'Hac ve Umre Organizasyon Paketleri',
    'Kültür, Doğa & Gezi Turları',
    'Kurumsal Kongre, Seminer, Fuar & Lansman',
    'Catering & Açık Büfe İkram Hizmetleri',
    'Ses, Işık, Truss & Sahne Sistemleri Kiralama'
  ],
  24: ['Işıklı & Işıksız Tabela', 'Billboard & Raket Reklam Üniteleri', 'Totem & Yönlendirme Panoları', 'Araç Giydirme & Cephe Kaplama', 'Fuar Standı Tasarım & Kurulumu', 'Dijital LED Ekran Sistemleri'],
  25: ['Peyzaj Proje & Uygulama', 'Otomatik Bahçe Sulama Sistemleri', 'Ağaçlandırma & Fidan Dikimi', 'Rulo Çim & Çimlendirme', 'Mevsimlik Çiçek & Süs Bitkileri', 'Budama, Çim Biçme & Bakım'],
  26: ['Büyükbaş & Küçükbaş Besi Yemi', 'Kanatlı Yemi & Premiks', 'Veteriner Aşı & İlaçları', 'Sağım & Ahır Ekipmanları', 'Canlı Hayvan Alım & Satımı', 'Suni Tohumlama Malzemeleri'],
  27: ['Bronz, Mermer & Fiber Heykel Yapımı', 'Mimari & Şehir Maketleri', 'Müzik Aletleri & Ses Teçhizatı', 'Geleneksel El Sanatları & Rölyef', 'Dekoratif Sanat Panoları'],
  28: ['Sanayi & Isınma Kömürü', 'Pelet & Briket Yakıtı', 'Odun & Odun Briketi', 'Kok Kömürü & Biyokütle Yakıt'],
  29: ['Toplu Tabldot Yemek Üretimi', 'Özel Davet & Protokol İkramları', 'Kumanya & Sandviç Paketleri', 'Kantin & Kafeterya İşletmeciliği', 'Hastane & Okul Diyet Menüleri'],
  30: ['Masaüstü PC & İş İstasyonları', 'Dizüstü Bilgisayar (Laptop)', 'Sunucu (Server) & Storage', 'Ağ Anahtarı (Switch) & Router', 'Lazer Yazıcı & Fotokopi Makineleri', 'Ölçü Aletleri (Multimetre, Osiloskop)'],
  31: ['IP Güvenlik Kamerası & NVR Sistemleri', 'Araç Takip & Filo Yönetimi GPS', 'SCADA & Uzaktan İzleme Telemetri', 'Telsiz & Trunk Haberleşme', 'Plaka Tanıma (PTS) Sistemleri'],
  32: [
    'Bina, Tesis & Ofis Temizliği',
    'Hastane & Sağlık Kuruluşu Hijyen Temizliği',
    'Okul, Üniversite & Yurt Temizliği',
    'Endüstriyel Fabrika & Atölye Temizliği',
    'Dış Cephe & Cam Temizleme',
    'Haşere & Kemirgen İlaçlama (Pest Kontrol)',
    'Dezenfeksiyon & Sterilizasyon Hizmetleri',
    'Geri Dönüşüm, Hurda & Atık Yönetimi',
    'Çöp Toplama & Katı Atık Nakliyesi'
  ],
  33: ['Kurumsal İş Kıyafetleri & Tulum', 'Güvenlik Görevlisi Üniformaları', 'Spor Kıyafetleri & Formalar', 'İş Ayakkabısı, Çizme & Çelik Burun', 'Termal İçlik & Yağmurluk', 'Spor Malzemeleri & Saha Donanımları'],
  34: ['Baret, Emniyet Kemeri & Yaşam Hattı', 'Koruyucu Gözlük & Kulaklık', 'Solunum Maskeleri (FFP2/FFP3/Gaz)', 'Yanmaz & Antistatik İş Elbiseleri', 'İlk Yardım & Acil Müdahale Dolapları', 'İSG Uyarı & İkaz Levhaları'],
  35: ['Silahlı & Silahsız Özel Güvenlik', 'Tesis & Şantiye Bekçilik Hizmeti', 'VIP Yakın Koruma & Refakat', 'Etkinlik & Konser Güvenliği', 'X-Ray & Kapı Dedektörü Operatörlüğü'],
  36: ['Yeminli Tercüme & Çeviri Hizmetleri', 'Kurumsal Personel Eğitimleri', 'Piyasa Araştırması & Anket Hizmeti', 'Mesleki Yeterlilik & Sertifikasyon', 'Akademik & Stratejik Raporlama'],
  37: ['Sosyal Tesis & Misafirhane İşletmeciliği', 'Danışma, Karşılama & Resepsiyon Hizmeti', 'Bina & Site Yönetim Hizmetleri', 'Bordrolama & Destek Personeli Temini', 'Posta, Evrak Dağıtım & Kurye'],
  38: ['Filo Kasko & Trafik Sigortası', 'Yangın & Deprem (DASK) Sigortası', 'Grup Sağlık & Ferdi Kaza Sigortası', 'Mali Müşavirlik & Bağımsız Denetim', 'Hukuki Danışmanlık & Tahkim'],
  39: ['Hacizli & Kurum İkinci El Araç Satışı', 'Hurda Demir, Bakır & Alüminyum', 'Hurda Kağıt, Karton & Plastik', 'Kullanım Dışı Elektronik Hurda (E-Atık)', 'Ekonomik Ömrünü Tamamlamış Taşıt Satışı'],
  40: ['Kamu & Özel Mülk Arsa Satışları', 'Ticari İşyeri & Dükkan İhaleleri', 'Kantin & Çay Ocağı Kiralama', 'Hizmet Binası & Depo Kiralama', 'Otopark İşletmesi Kiralama İhaleleri']
};

export const TENDER_TYPES = [
  'Tümü',
  'Mal Alımı',
  'Hizmet Alımı',
  'Yapım İşi (İnşaat)',
  'Danışmanlık',
  'Satış & Kiralama'
];

export const TENDER_METHODS = [
  'Tümü',
  'Açık Eksiltme (Ters İhale)',
  'Açık Artırma',
  'Kapalı Zarf Usulü',
  'Sabit Fiyatlı Paket & Kontenjan',
  'Doğrudan Temin / Fiyat Araştırması',
  'Pazarlık Usulü'
];

export const COMMON_TAX_OFFICES = [
  'Çanakkale Vergi Dairesi Müdürlüğü',
  'İstanbul Büyük Mükellefler Vergi Dairesi',
  'İstanbul Beşiktaş Vergi Dairesi',
  'İstanbul Kadıköy Vergi Dairesi',
  'Ankara Kızılbey Vergi Dairesi',
  'Ankara Çankaya Vergi Dairesi',
  'İzmir Kordon Vergi Dairesi',
  'İzmir Konak Vergi Dairesi',
  'Bursa Osmangazi Vergi Dairesi',
  'Balıkesir Karesi Vergi Dairesi',
  'Kocaeli Alemdar Vergi Dairesi',
  'Gaziantep Şahinbey Vergi Dairesi',
  'Antalya Muratpaşa Vergi Dairesi',
  'Adana Seyhan Vergi Dairesi',
  'Konya Mevlana Vergi Dairesi',
  'Tekirdağ Süleymanpaşa Vergi Dairesi'
];
